name: GriefPrevention
main: me.ryanhamshire.GriefPrevention.GriefPrevention
softdepend: [Vault, Multiverse-Core, My Worlds, MystCraft, Transporter]
dev-url: http://dev.bukkit.org/server-mods/grief-prevention
version: 7.8
commands:
   gphelp:
      description: GriefPrevention Advanced Help command
      usage: /gp [topic]
   setclaimblocks:
      description: sets the claim blocks for a player to a specific value.
      usage: /SetClaimBlocks <player> <amount>
      permission: griefprevention.commands.setclaimblocks
   claiminfo:
      description: displays advanced information about a claim.
      usage: /ClaimInfo [claimid]
      permission: griefprevention.commands.claiminfo
   cleanclaim:
      description: cleans all of a given material from a owned claim. target material defaults to AIR.
      usage: /CleanClaim <source> <target>
      permission: griefprevention.commands.cleanclaim
   cleanclaims:
      description: performs a manual Claim Cleanup. This will delete and remove claims where the owner has not been online in a while and where the claim doesn't have much invested in it.
      usage: /CleanClaims
      permission: griefprevention.commands.cleanclaims
   clearmanagers:
      description: Clears all managers on a claim.
      usage: /ClearManagers
      permission: griefprevention.commands.clearmanagers
   abandonclaim:
      description: Deletes a claim.
      usage: /AbandonClaim
      permission: griefprevention.commands.abandonclaim
   abandontoplevelclaim:
      description: Deletes a claim and all its subdivisions.
      usage: /AbandonTopLevelClaim
      permission: griefprevention.commands.abandontoplevelclaim
   abandonallclaims:
      description: Deletes ALL your claims.
      usage: /AbandonAllClaims
      permission: griefprevention.commands.abandonallclaims
   trust:
      description: Grants a player full access to your claim(s).
      usage: /Trust <player>  Grants a player permission to build.  See also /UnTrust, /ContainerTrust, /AccessTrust, and /PermissionTrust.
      aliases: tr
      permission: griefprevention.commands.trust
   untrust:
      description: Revokes a player's access to your claim(s).
      usage: /UnTrust <player>
      aliases: ut
      permission: griefprevention.commands.untrust
   containertrust:
      description: Grants a player access to your containers.
      usage: /ContainerTrust <player>.  Grants a player access to your inventory, bed, and buttons/levers.
      aliases: ct
      permission: griefprevention.commands.containertrust
   accesstrust:
      description: Grants a player entry to your claim(s) and use of your bed.
      usage: /AccessTrust <player>.  Grants a player access to your bed, buttons, and levers.
      aliases: at
      permission: griefprevention.commands.accesstrust
   permissiontrust:
      description: Grants a player permission to grant his level of permission to others.
      usage: /PermissionTrust <player>.  Permits a player to share his permission level with others.
      aliases: pt
      permission: griefprevention.commands.permissiontrust
   subdivideclaims:
      description: Switches the shovel tool to subdivision mode, used to subdivide your claims.
      usage: /SubdivideClaims
      aliases: sc
      permission: griefprevention.commands.subdivideclaims
   adjustbonusclaimblocks:
      description: Adds or subtracts bonus claim blocks for a player.
      usage: /AdjustBonusClaimBlocks <player> <amount>
      permission: griefprevention.commands.adjustbonusclaimblocks
      aliases: acb
   adjustaccruedclaimblocks:
      description: Adds or subtracts accrued claim blocks for a player.
      usage: /AdjustAccruedClaimBlocks <player> <amount>
      permission: griefprevention.commands.adjustaccruedclaimblocks
      aliases: aab
   transferclaimblocks:
      description: transfers claim blocks from one player to another.
      usage: /TransferClaimBlocks <sourceplayer> <targetplayer> <amount>
      permission: griefprevention.commands.transferclaimblocks
   setblockbank:
      description: Set the player's accrued blocks bank to the specified amount.
      usage: /SetBlockBank <player> <amount>
      permission: griefprevention.commands.setblockbank
      aliases: sbb
   deleteclaim:
      description: Deletes the claim you're standing in, even if it's not your claim.
      usage: /DeleteClaim
      permission: griefprevention.commands.deleteclaim
      aliases: dc   
   deleteallclaims:
      description: Deletes all of another player's claims.
      usage: /DeleteAllClaims <player>
      permission: griefprevention.commands.deleteallclaims
   resetclaims:
      description: Deletes all of another player's claims AND resets their accrued block bank to the initial value.
      usage: /ResetClaims <player>
      permission: griefprevention.commands.resetclaims
   adminclaims:
      description: Switches the shovel tool to administrative claims mode.
      usage: /AdminClaims
      permission: griefprevention.commands.adminclaims
      aliases: ac
   restorenature:
      description: Switches the shovel tool to restoration mode.
      usage: /RestoreNature 
      permission: griefprevention.commands.restorenature
      aliases: rn
   restorenatureaggressive:
      description: Switches the shovel tool to aggressive restoration mode.
      usage: /RestoreNatureAggressive 
      permission: griefprevention.commands.restorenatureaggressive
      aliases: rna
   restorenaturefill:
      description: Switches the shovel tool to fill mode.
      usage: /RestoreNatureFill <radius> 
      permission: griefprevention.commands.restorenaturefill
      aliases: rnf
   basicclaims:
      description: Switches the shovel tool back to basic claims mode.
      usage: /BasicClaims
      aliases: bc
      permission: griefprevention.commands.basicclaims
   buyclaimblocks:
      description: Purchases additional claim blocks with server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /BuyClaimBlocks <numberOfBlocks>
      aliases: buyclaim   
      permission: griefprevention.commands.buyclaimblocks
   sellclaimblocks:
      description: Sells your claim blocks for server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /SellClaimBlocks <numberOfBlocks>
      aliases: sellclaim
      permission: griefprevention.commands.sellclaimblocks
   trapped:
      description: Ejects you to nearby unclaimed land.  Has a substantial cooldown period.
      usage: /Trapped
      permission: griefprevention.commands.trapped
   trustlist:
      description: Lists permissions for the claim you're standing in.
      usage: /TrustList
      permission: griefprevention.commands.trustlist
   siege:
      description: Initiates a siege versus another player.
      usage: /Siege <playerName>
      permission: griefprevention.commands.siege
   ignoreclaims:
      description: Toggles ignore claims mode.
      usage: /IgnoreClaims
      permission: griefprevention.commands.ignoreclaims
      aliases: ic
   ignore:
      description: Ignores a Player, or displays your current ignore list.
      usage: /Ignore [Player]
      permission: griefprevention.commands.ignore
   softmute:
      description: Mutes a player, making their messages not display for most server players.
      usage: /SoftMute <Player>
      permission: griefprevention.commands.softmute
   deletealladminclaims:
      description: Deletes all administrative claims.
      usage: /DeleteAllAdminClaims
      permission: griefprevention.commands.deletealladminclaims
   transferclaim:
      description: Converts an administrative claim to a private claim or a private claim to an administrative claim.
      usage: /TransferClaim [targetplayer]
      permission: griefprevention.commands.transferclaim
   giveclaim:
      description: Gives a claim to another player. Requires AdminClaims permission to give a claim that doesn't belong to the player.
      usage: /GiveClaim <TargetPlayer>
      permission: griefprevention.commands.giveclaim
   deathblow:
      description: Kills a player, optionally giving his inventory to another player.
      usage: /DeathBlow <player> [recipientPlayer]
      permission: griefprevention.commands.deathblow
   claimslist:
      description: Lists information about a player's claim blocks and claims.
      usage: /ClaimsList or /ClaimsList <player>
      permission: griefprevention.commands.claimslist
   claimexplosions:
      description: Toggles whether explosives may be used in a specific land claim.
      usage: /ClaimExplosions
      permission: griefprevention.commands.claimexplosions
   lockclaim:
      description: Locks the claim from accidental mass/automatic deletion.
      usage: /LockClaim
      permission: griefprevention.commands.lockclaim
   unlockclaim:
      description: Unlocks a previously locked claim.
      usage: /UnlockClaim
      permission: griefprevention.commands.unlockclaim
   gpreload:
      description: reloads GP configuration.
      usage: /gpreload
      permission: griefprevention.commands.gpreload
   gpdebug:
      description: sets GriefPrevention debug options. 
      usage: /gpdebug <option> <value>
      permission: griefprevention.commands.gpdebug
   viewbook:
      description: Allows copying of books for eavesdropping purposes. 
      usage: /viewbook <id>
      permission: griefprevention.commands.viewbook
      
permissions:
    griefprevention.basicclaimcommands:
        description: Grants access to Basic GriefPrevention claim commands.
        children:
            griefprevention.commands.trust: true
            griefprevention.commands.untrust: true
            griefprevention.commands.accesstrust: true
            griefprevention.commands.containertrust: true
            griefprevention.commands.permissiontrust: true
            griefprevention.commands.claimexplosions: true
    griefprevention.commands.setclaimblocks:
        description: Grants access to the setclaimblocks command.
        default: op
    griefprevention.commands.claiminfo:
        description: Grants access to the claiminfo command.
        default: op
    griefprevention.commands.claimexplosions:
        description: Grants access to the claimexplosions command.
        default: true
    griefprevention.commands.cleanclaim:
        description: Grants access to the cleanclaim command.
        default: op
    griefprevention.commands.cleanclaims:
        description: Grants access to the cleanclaims command.
        default: op
    griefprevention.commands.clearmanagers:
        description: Grants access to the clearmanagers command.
        default: true
    griefprevention.commands.abandonclaim:
        description: Grants access to the abandonclaim command.
        default: true
    griefprevention.commands.abandontoplevelclaim:
        description: Grants access to the abandontoplevelclaim command.
        default: true
    griefprevention.commands.abandonallclaims:
        description: grants access ot the abandonallclaims command.
        default: true
    griefprevention.commands.trust:
        description: grants access to the trust command.
        default: true
    griefprevention.commands.untrust:
        description: grants access to the untrust command.
        default: true
    griefprevention.commands.containertrust:
        description: grants access to the container trust command.
        default: true
    griefprevention.commands.accesstrust:
        description: grants access to the accesstrust command.
        default: true
    griefprevention.commands.permissiontrust:
        description: grants access to the permissiontrust command.
        default: true
    griefprevention.commands.subdivideclaims:
        description: grants access to the subdivideclaims command.
        default: true
    griefprevention.commands.adjustbonusclaimblocks:
        description: grants access to the adjustbonusclaimblocks command.
        default: op
    griefprevention.commands.adjustaccruedclaimblocks:
        description: grants access to the adjustaccruedclaimblocks command.
        default: op
    griefprevention.commands.transferclaimblocks:
        description: grants access to the transferclaimblocks command.
        default: op
    griefprevention.commands.setblockbank:
        description: grants access to the setblockbank command.
        default: op
    griefprevention.commands.deleteclaim:
        description: grants access to the deleteclaim command.
        default: op
    griefprevention.commands.deleteallclaims:
        description: grants access to the deleteallclaims command.
        default: op
    griefprevention.commands.resetclaims:
        description: grants access to the resetclaims command.
        default: op
    griefprevention.commands.adminclaims:
        description: grants access to the adminclaims command.
        default: op
    griefprevention.commands.restorenature:
        description: grants access to the restorenature command.
        default: op
    griefprevention.commands.restorenatureaggressive:
        description: grants access to the restorenatureaggressive command.
        default: op
    griefprevention.commands.restorenaturefill:
        description: grants access to the restorenaturefill command.
        default: op
    griefprevention.commands.basicclaims:
        description: grants access to the basicclaims command.
        default: true
    griefprevention.commands.buyclaimblocks:
        description: grants access to the buyclaimblocks command
        default: true
    griefprevention.commands.sellclaimblocks:
        description: grants access to the sellclaimblocks command
        default: true
    griefprevention.commands.trapped:
        description: grants access to the trapped command.
        default: true
    griefprevention.commands.trustlist:
        description: grants access to the trustlist command.
        default: true
    griefprevention.commands.siege:
        description: grants access to the siege command.
        default: true
    griefprevention.commands.ignoreclaims:
        description: grants access to the ignoreclaims command.
        default: op
    griefprevention.commands.ignore:
        description: grants access to the ignore command.
        default: op
    griefprevention.commands.softmute:
        description: grants access to the softmute command.
        default: op
    griefprevention.commands.deletealladminclaims:
        description: grants access to the deletealladminclaims command.
        default: op
    griefprevention.commands.transferclaim:
        description: grants access to the transferclaim command.
        default: op
    griefprevention.commands.giveclaim:
        description: grants access to the giveclaim command.
        default: true
    griefprevention.commands.deathblow:
        description: grants access to the deathblow command.
        default: op
    griefprevention.commands.claimslist:
        description: grants access to the claimslist command.
        default: true
    griefprevention.commands.lockclaim:
        description: grants access to the lockclaim command.
        default: true
    griefprevention.commands.unlockclaim:
        description: grants access to the unlockclaim command.
        default: true
    griefprevention.commands.gpreload:
        description: grants access to the gpreload command.
        default: op
    griefprevention.commands.gpdebug:
        description: grants access to the gpdebug command.
        default: op
    griefprevention.commands.viewbook:
        description: grants access to the viewbook command.
        default: op
    griefprevention.claims.transfer:
        description: grants access to allow transfer of claims.
        default: op
    griefprevention.placement.water:
        description: Allow access to place water in applicable locations.
        default: op
    griefprevention.placement.lava:
        description: Allow access to place Lava in applicable locations.
        default: op
    griefprevention.claims.ignorelimit:
        description: Allows creation of more claims than any configured per-player limit.
        default: false
    griefprevention.claims.chestcreate:
        description: Grants permission to create claims.
        default: true
    griefprevention.claims.toolcreate:
        description: Grants permission to use the Shovel or other claim tool to create claims.
        default: true
    griefprevention.admin.*:
        description: Grants all administrative functionality.
        children:
            griefprevention.commands.*: true
    griefprevention.admin.claims:
        description: Grants permission to create administrative claims.
        default: op
    griefprevention.claims.delete:
        description: Grants permission to delete other players' claims.
        default: op
    griefprevention.spam:
        description: Grants permission to send messages commands rapidly.
        default: op
    griefprevention.spam.login:
        description: Grants permission to log in rapidly.
        default: op
    griefprevention.placement.lava:
        description: Grants permission to place lava near the surface and outside of claims.
        default: op
    griefprevention.placement.water:
        description: Grants permission to place water near the surface and outside of claims.
        default: true
    griefprevention.eavesdrop.standard:
        description: Allows a player to see whispered chat messages (/tell).
        default: op
    griefprevention.admin.eavesdrop:
        description: Allows a player to see all whispered chat messages (/tell).
        default: op
    griefprevention.claims.lock:
        description: Grants permission to use the lock/unlock commands on your own claims.
        default: op
    griefprevention.admin.lock:
        description: Grants permission to use the lock/unlock commands on any claim.
        default: op
    griefprevention.spam.notignorable:
        description: Makes a Player impossible to ignore using the /ignore command.
        default: op